### ISSUE TITLE
Feature Request: Navigation button on scm/title

### ISSUE THREAD

**Issue by lens0021** [phil294/git-log--graph#15]
The navigation button on scm/title is one of my favorite features of vscode-git-graph and even ~~GitKraken~~GitLens provides it.

![Screenshot from 2023-05-22 10-27-01](https://github.com/phil294/git-log--graph/assets/28209361/cd572fde-818d-4f4e-b425-89dda421757a)

I tried to implement this myself and [here](https://github.com/lens0021/git-log--graph/commit/6dfe5846b742ecb3d5c39fc82dbf8d2041a1b28d) is my WIP code which is used to make the above image, but I could not figure out how to implement the backend part.

**Comment by phil294** [comment]
neat, also didn't know this existed. Your changes work fine for me. I guess you just forgot to do `yarn serve` in the web folder? (see `CONTRIBUTING.md`)

you don't have to test this though, we can just merge it now

**Comment by lens0021** [comment]
The problem is that if multiple repositories are open, the buttons do not work expectedly. I want each buttons for each repository to act differently, but all do the same thing.
