### ISSUE TITLE
[Feature] Add explanations to common options

### ISSUE THREAD

**Issue by pktiuk** [phil294/git-log--graph#17]
I think it would be good to add simple explanations to Common options. It would make using them more understandable for people not very familiar with git.

![image](https://github.com/phil294/git-log--graph/assets/45544416/7a215189-87ae-41c7-a22d-848143b3b6b0)

**Comment by phil294** [comment]
I like your suggestion and I also thought about the same thing yesterday. Apart from better UX in general, it would also allow for complicated/obscure options to be passed with a simple description. For example,

```json
{
  "description": "Hide merge commits",
  "contents": "--grep=\"Merge branch '\" --grep=\"Merge remote tracking branch '\""
  "default_active": false
}
```

**Comment by phil294** [comment]
![image](https://github.com/phil294/git-log--graph/assets/14108705/7d909441-d30d-454e-bed2-bab05c7da1b5)

so the hide merge commits option is now also there and the common texts, taken from `git help ...`. It's the best I could come up with for now, suggestions welcome of course. I definitely do not want to write custom texts for all options manually, but I think the git manual is quite good.

**Comment by pktiuk** [comment]
> the common texts, taken from git help .... 

I think it is a great idea. But in some cases it would be good to override these automatic descriptions with manually written ones.

**Comment by phil294** [comment]
ok sure, feel free to send them in :-)
