### ISSUE TITLE
[Feature] Simplify hiding remote branches

### ISSUE THREAD

**Issue by pktiuk** [phil294/git-log--graph#18]
This is the first function I missed after opening this extension.

These should be either just a simple checkbox to tick next to `Filter` radio button or another common option in `Configure...` field.

**Comment by phil294** [comment]
Definitely still a missing feature. Should these remote branches then disappear everywhere or stay somewhere to be discovered? My suggestion would be to hide them from the main listing and hide them from the "All branches" list but still show remote branches in commit details, if a commit has any.

**Comment by pktiuk** [comment]
>  My suggestion would be to hide them from the main listing and hide them from the "All branches" list but still show remote branches in commit details, if a commit has any.

I think this is a good idea. Even in case of huge repositories with many branches showing branches only in commit details would not be a problem.

**Comment by phil294** [comment]
![image](https://github.com/phil294/git-log--graph/assets/14108705/25089770-8ad9-4456-b5c8-5a56a0cd3930)

I put the thing into the `Configure...` field now as it's definitely to be configured as a `git log` argument option.
