### ISSUE TITLE
Provide web version

### ISSUE THREAD

**Issue by Trass3r** [phil294/git-log--graph#2]
So it can be used in github.dev and the like.
First step is to bundle it using esbuild/webpack/etc.

https://code.visualstudio.com/api/extension-guides/web-extensions#migrate-extension-with-code

**Comment by phil294** [comment]
Sounds good, but how would a web extension execute git commands (the entire purpose of this extension)?

**Comment by Trass3r** [comment]
Haven't though about that. Maybe there is a library which can do that? Somehow vscode has to do it too, the source control view with modified files works in the web version. Just can't see any history.

**Comment by phil294** [comment]
so I don't know what and how vscode does it, but I guess this works via GitHub integration? In other words, there are no actual git commands executed but GH api is queried. If that is the case, imitating this is probably a lot of work as it isn't compatible with the basic execution approach this extension is built on, see the two code sample lines [here](https://github.com/phil294/git-log--graph/blob/master/CONTRIBUTING.md). It would also make configurable user git actions impossible, imo the biggest selling point of this project.

What this mostly needs to proceed is someone investing time and research effort.

**Comment by phil294** [comment]
come to think about it, this is pretty much impossible with the current architecture, or at least completely out of scope. Thanks for the suggestion anyway.
