### ISSUE TITLE
Missing Dev dependancies

### ISSUE THREAD

**Issue by reporter123** [phil294/git-log--graph#21]
package.json has no dev dependencies. You further document to you are unable to upgrade certain dependencies an this time. I can sort what the dependencies are but have no way to guess what versions you use.

**Comment by lens0021** [comment]
Have you checked https://github.com/phil294/git-log--graph/blob/master/CONTRIBUTING.md and https://github.com/phil294/git-log--graph/blob/master/web/package.json?

**Comment by reporter123** [comment]
Thanks.
