### ISSUE TITLE
Doesn't open when clicking the status bar button or running the command on first load

### ISSUE THREAD

**Issue by yougotwill** [phil294/git-log--graph#29]
**When you first open VS Code**, you have to actually click the panel to load git-log--graph. It won't open when you click the status bar button or when you run the open git-log--graph command. After that initial load everything works fine.

Example:

https://github.com/phil294/git-log--graph/assets/14887287/29d3473c-dafd-4f1a-a246-4aa8255ef746

**Comment by phil294** [comment]
this may actually be a design limitation by vscode :-/ needs some more investigation though

**Comment by yougotwill** [comment]
Ah no worries. Appreciate you looking into it. Hopefully if it is a limitation we can log an issue on their repo. Happy to do it if you send the details after your investigation

**Comment by yougotwill** [comment]
@phil294 This seems to be fixed as of v.0.1.8. Not sure what you did but thanks! Feel free to close

**Comment by phil294** [comment]
whaaa..?? no idea why but I'll take it

**Comment by yougotwill** [comment]
It seems to only have been fixed on my work machine (iMac 2019) and not my personal (Macbook Pro 2018) I imagine it's a VS Code issue and unrelated to the extension so I won't reopen the issue. Just leaving a note here in case other people have the same issue.
