### ISSUE TITLE
Rare characters

### ISSUE THREAD

**Issue by shdwchn10** [phil294/git-log--graph#3]
First of all, thank you for your extension!

I want to warn you that you use quite rare characters in your extension and want to help other users find the fonts they need.

So here is the list:
- emoji (Delete button) — Google Noto Emoji (Fedora Linux packages: `google-noto-emoji-fonts google-noto-emoji-color-fonts`). Almost certainly these fonts are already preinstalled in the system
- ⥁ , ⛙, etc (Checkout/Merge/etc buttons) — Symbola font (Fedora Linux package: `gdouros-symbola-fonts`)
- 𖣣  (Cherry pick button) — Google Noto Sans Bamum (Fedora Linux package: `google-noto-sans-bamum-fonts`)

![Screenshot from 2022-10-25 18-13-41](https://user-images.githubusercontent.com/79763381/197812915-2917ab8e-3e77-4b0b-a8e7-70e6b5512737.png)

**Comment by phil294** [comment]
Hi @shdwchn10,

great, thanks for your research. These icons aren't mandatory, I usually just google things like "revert unicode", browse through a few results and copy-paste the one I like the most. It spares the necessity for yet another external dependency such as Font Awesome, and it makes for easy configurability (it's all just strings).

So I think we can easily fix this and instead switch to icons that should be present on all common systems. Do you have any suggestion on how to figure out which icons to use? I need some sort of replacements for the more exotic ones, and also I'm sure there will be more actions coming along that should be shown by default.

**Comment by shdwchn10** [comment]
[todo-tree](https://github.com/Gruntfuggly/todo-tree/#highlighting) (see `icon` parameter) uses [vscode-codeicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html) and [Octicons](https://primer.style/octicons/). IIRC vscode-codeicons should be available out of the box on any of VS Code variant (official, OSS, VS Codium, etc) and on any supported OS.

**Comment by phil294** [comment]
right, that looks good. I'll switch to those icons then very soon. (sorry, I kind of forgot about this issue)

**Comment by phil294** [comment]
should be fixed now. looks like this:

![imagen](https://user-images.githubusercontent.com/14108705/212596039-a4698fde-860d-42bd-87b5-11448d0cd1cd.png)

![imagen](https://user-images.githubusercontent.com/14108705/212596075-45576b7d-163c-4738-83a6-205c89af3fd4.png)
