### ISSUE TITLE
Icons fail to render correctly

### ISSUE THREAD

**Issue by yougotwill** [phil294/git-log--graph#41]
Just updated to v0.1.9 and none of the icons are loading correctly. Just have squares.

<img width="1351" alt="Screenshot 2023-06-22 at 10 13 33 am" src="https://github.com/phil294/git-log--graph/assets/14887287/8769e028-11ef-438d-b47d-9cd112ba8b87">

**Comment by phil294** [comment]
oops, sorry. It was fine in development mode... I just added a short step to my release script which I will run before every update now - now I can quickly verify that everything still works as expected in production mode too.

so yeah, should work again fine now.
