### ISSUE TITLE
Empty narrow hoverable lines in the commit list

### ISSUE THREAD

**Issue by adalisk-emikhaylov** [phil294/git-log--graph#43]
The commit list shows a few narrow lines that change the color when hovered.

![image](https://github.com/phil294/git-log--graph/assets/69473580/afbe3f22-a14f-44ab-a316-ee87aa2ab20f)

This is probably caused by how you parse the `git log --graph` output.

**Comment by adalisk-emikhaylov** [comment]
After reading https://github.com/phil294/git-log--graph/issues/22 I understand that this was intentional.

Then my suggestion would be to remove the hover effect from those lines. Perhaps connect the detached line segments together to make it look smoother.

**Comment by phil294** [comment]
> Then my suggestion would be to remove the hover effect from those lines.

ok

> Perhaps connect the detached line segments together to make it look smoother.

I want that too, but it's probably a bit tricky. The visualization parser is really dumb (just ascii transforming) right now.
