### ISSUE TITLE
Does not load command line on startup

### ISSUE THREAD

**Issue by hansu** [phil294/git-log--graph#48]
To load the specified git command you have to press "Execute", it is not applied automatically when starting git-log--graph:

![git-log-graph-bug-execute](https://github.com/phil294/git-log--graph/assets/67957916/c7bbdaf9-0bf8-43f3-9fdb-b5f687adcff3)

**Comment by phil294** [comment]
this bug behaved a bit differently for me - the first attempt indeed showed the wrong data, but a second one came after that fixed it. I have now fixed the first and removed the second, and also fixed some other bugs, so maybe it works fine for you now, maybe not. If not, can you please launch the extension with `"git-log--graph.verbose-logging": true` set and copy the `OUTPUT`/`git log --graph` contents into this issue? (possibly stripping it of sensitive data)

**Comment by hansu** [comment]
Thanks, works fine for me now :+1:
