### ISSUE TITLE
Don't use width-ratio for search bar

### ISSUE THREAD

**Issue by hansu** [phil294/git-log--graph#50]
Not sure exactly how it's implemented, but it feels like the columns in the search bar (folder name, description, search entry, radio buttons, buttons) all have a fixed percentage of the available width. So it happens if the window width is small, the buttons will be cut off:
![git-log-graph-search-bar](https://github.com/phil294/git-log--graph/assets/67957916/4cacf122-fc5b-4601-9b0a-f85053e5c2f8)

Suggestion:
- Fixed width and right align the buttons so that only the search entry will be resized.
- The description text "Jump between matches with ENTER / SHIFT + ENTER" could be shown as a tooltip - it doesn't need to be shown always. (By the way - why not using the standard keys F3 / Shift+F3 for this?)

**Comment by phil294** [comment]
agreed!

> - why not using the standard keys F3 / Shift+F3 for this?

I was under the impression that <kbd>Ctrl</kbd>+<kbd>F</kbd> and then <kbd>Enter</kbd> / <kbd>Shift</kbd>+<kbd>Enter</kbd> was the common, "standard" way of doing this in pretty much every application :-) but it seems F3 is pretty common too, so I guess we should just add both.

**Comment by phil294** [comment]
this is mostly fixed now. still a bit rough when there's **very** little space though

**Comment by hansu** [comment]
Thank you!
