### ISSUE TITLE
The first checkboxes seem to be missing on Dialogs

### ISSUE THREAD

**Issue by lens0021** [phil294/git-log--graph#64]
For example, "Record Origin" checkbox is not shown on Cherry Pick Dialog, while https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#dialog assumes there are checkboxes I cannot see.

![image](https://github.com/mhutchie/vscode-git-graph/assets/28209361/a2b196d6-f7dd-4ab5-85e1-dd0ac348e192)
![image](https://github.com/mhutchie/vscode-git-graph/assets/28209361/9271b7a4-222c-4f21-83ca-e010a61facd5)

I am using the default settings.
Extension Version: v0.1.13

**Comment by phil294** [comment]
hi @lens0021, these are two different extensions. mhutchie's codebase is unrelated to this one.

**Comment by phil294** [comment]
however, perhaps the default options should be extended? cherry-pick record-origin sounds like a useful one to start with. There's just so many - how should we define what needs to be provided as checkboxes and what isn't (because it is so rarely used it is more of an obstacle but a help)
