### ISSUE TITLE
`vscode.git` API on NPM

### ISSUE THREAD

**Issue by Malix-off** [phil294/git-log--graph#65]
Hey guys!

I recently discovered you were also using the `vscode.git` API;
Meaning you face the same problem as me which is to deal with its terrible delivery (see https://github.com/microsoft/vscode/issues/198592).

I feature-requested a better delivery (publish on NPM, basically) here: https://github.com/microsoft/vscode/issues/198592.

It technically needs 20 👍 to be accepted into the backlog, so I'm sharing it with you if you find interesting

Thanks and have a very great day!

**Comment by phil294** [comment]
I don't see this as a pressing issue personall, but indeed the current process of copy/paste is quite questionable. So definitely worth an upvote, you got mine at least.

Closing as I'm the only developer here right now
