### ISSUE TITLE
Bug: no auto-scroll when window is already open.

### ISSUE THREAD

**Issue by pgsandstrom** [phil294/git-log--graph#67]
Lets say the extension window is not open. In a file editor I see in the gutter the blame for a certain line, something like "Per Sandström, last year". When I click it, this extension opens and it correctly auto-scroll down to the correct position to show me the newly selected commit I just clicked.

But if the extension window is already open when I do this, it does not auto-scroll to the newly selected commit.

Let me know if this is unclear in any way. I could arrange a video recording if needed.

**Comment by phil294** [comment]
thanks, all clear! fixed with v0.1.14
