### ISSUE TITLE
Filter/search also with long hash

### ISSUE THREAD

**Issue by hansu** [phil294/git-log--graph#68]
Git log graph doesn't find the commit if searching or filtering after the commit hash in the long format because it filters/searches only what is displayed. And the short one is displayed.

**Comment by phil294** [comment]
fixed with v0.1.14, and the long hashes are now also shown in the right commit details pane or on hover on the small hashes in the main view.

**Comment by hansu** [comment]
Great, thanks!
Now I am missing the possibility to copy the long hash to the clipboard :D
Should I create a new issue for that?
I suggest adding an entry in the context menu like it is done in [Git Graph](https://github.com/phil294/git-log--graph/assets/67957916/438cb9eb-c3c3-4c22-87ed-17f264d5d11b). Or a button in the details view if you don't want to overload the context menu.

**Comment by phil294** [comment]
is that really such a frequent thing to do? You can simply click on a commit, and scroll down the right details view to the bottom, double click the long hash and press ctrl+c. You'd just like to have a shortcut for that, correct?

**Comment by phil294** [comment]
#76 is a separate issue for that

**Comment by hansu** [comment]
> is that really such a frequent thing to do? You can simply click on a commit, and scroll down the right details view to the bottom, double click the long hash and press ctrl+c. You'd just like to have a shortcut for that, correct?

First I didn't know that the long hash appears at the bottom. For commits with only a few changed files this is ok, but if you first have to scroll down the commits...
I often do things like `git rebase -i <hash>~1 ` or similar. therefore it it handy to have to get the hash quickly. 
I know this is possible with the context menu shortcut, but complex things I prefer to do in the bash.
