### ISSUE TITLE
Don't snap to commits while scrolling

### ISSUE THREAD

**Issue by samfundev** [phil294/git-log--graph#7]
When scrolling [the extension snaps to the nearest commit](https://github.com/phil294/git-log--graph/blob/84b042aab7f91c1084169efdd97330d75b56d2fc/web/src/views/MainView.coffee#L185), this can make scrolling look very jittery when scrolling slowly:
![jitter](https://github.com/phil294/git-log--graph/assets/6759716/c15130d9-673c-463d-ad59-b884c02bfabd)

Personally, I'd much rather see half a commit than have the view jitter when I scroll.

**Comment by phil294** [comment]
yes I can see how that is annoying. I was also not super happy with how it worked. As the link says, it's done like this so the dotted connection lines at the top always reach their target. I now changed the logic so it doesn't snap after scrolling, instead it now prevents natural scrolling and injects custom scrolling speed / steps for any wheel or up/down events. I normally hate it when websites/apps do that but in this case, it still seems like the best solution. I'd be curious what you think! It's now released as version 0.1.3.

However, configurability is always nice so I added an option, `git-log--graph.disable-scroll-snapping`, which you can set to prevent that and indeed see half commits.

**Comment by samfundev** [comment]
The new scrolling is awesome! Thanks for the change.
