### ISSUE TITLE
Unable to search for commits with upper case

### ISSUE THREAD

**Issue by Amanoki** [phil294/git-log--graph#72]
If the commit message contains uppercase letters, the uppercase letters will be ignored by the search.

For example, there are two commits "Add: File" and "add: file".
Search for "A / Add / add / File / file", only "add: file" will show up.
Search for "dd" (without "A") or "ile" (without F), both commits will show up.
Expect: "Add: File" should show up as well when the search keyword contains its uppercase part.

**Comment by phil294** [comment]
fixed with v0.1.14. now everything is case insensitive, as it should have been from the start. even better would be configurability some day
