### ISSUE TITLE
Error when clicking on empty commits

### ISSUE THREAD

**Issue by Amanoki** [phil294/git-log--graph#73]
If an empty commit is clicked when the right panel is active, the following error will pop up:
```
git-log--graph: git log --graph extension encountered an unexpected error. Sorry! Error summary: Cannot read properties of undefined (reading 'split'). For details, see VSCode developer console. Please consider reporting this error.
```

**Comment by phil294** [comment]
fixed with v0.1.14

**Comment by phil294** [comment]
such exotic bug reports you have brought in! amazing :D

**Comment by Amanoki** [comment]
Thank you for the quick fix!
I really love the configurability of this extension, good job!
