### ISSUE TITLE
Non-English filenames are not displayed correctly in the right panel

### ISSUE THREAD

**Issue by Amanoki** [phil294/git-log--graph#74]
When the filenames contain non-English characters such as Chinese, Japanese characters, they will be displayed as numbers in the right panel. It would be great if it supports non-English characters.
![1233](https://github.com/phil294/git-log--graph/assets/46240634/75f9f50b-2ebc-4e87-8a77-f7a839860214)

**Comment by phil294** [comment]
fixed with v0.1.14
