### ISSUE TITLE
Ctrl Click = Right mouse button click on MAC OS prevents file comparison.

### ISSUE THREAD

**Issue by msarchioni-mwb** [phil294/git-log--graph#79]
In Mac OS the right mouse button click is emulated by Ctrl + click (left). Given that in Mac OS Sonoma (14.3.1) seems to be impossible disable this behaviour, this will prevent to compare two different branches or commits distant in time.
It would be nice to consider also the command key in Mac OS or give the user the possibility to customise the key combination.

**Comment by phil294** [comment]
fixed with version 0.1.15
