### ISSUE TITLE
Work with "Floating editor windows"

### ISSUE THREAD

**Issue by dimateos** [phil294/git-log--graph#85]
Similarly to git-graph (recycled the picture), the current view does not work with ["Floating editor windows"](https://code.visualstudio.com/updates/v1_85#_floating-editor-windows):

![image](https://github.com/phil294/git-log--graph/assets/26868611/fe5ca8ff-3dfc-4be4-b290-c0bb93913506)

**Comment by dimateos** [comment]
vscode updated some time ago so that most webviews already work in floating windows. Such is the case.

**Comment by phil294** [comment]
awesome!
