### ISSUE TITLE
Add a keyboard shorcut for reloading

### ISSUE THREAD

**Issue by yougotwill** [phil294/git-log--graph#89]
Hey, as always appreciate you building this extension and it's now a dedicated part of my workflow. Thank you.

I tend to run git fetch and pull commands via the VSCode command palette and from the terminal and I have to press the reload button in git log --graph to refresh the view. It would be great if we could have a shortcut (can be unassigned by default) that I can use to reload the view because right now I have to use my mouse every time to do it and it breaks my flow a bit.

Keep up the awesome work 🚀

**Comment by phil294** [comment]
implemented with version 0.1.15: Extensions shouldn't (can't?) define shortcuts by themselves, but there is now a new command "git-log--graph: Refresh". You can go into shortcuts and assign anything to it you want.

I was thinking to perhaps add commands for more other actions too like global abort or current branch push etc... but there's mostly already existing commands for that already, and this can also be abstracted into bash commands etc already without the need for this extension

**Comment by yougotwill** [comment]
Thank you! And yes I agree. It's better for the extension to be focused on implementing features that aren't already possible via VSCode or the terminal nicely.
